defaults:
  - base_neo
  - _self_

batch_size: 128

structure: 10@512

epoch: 200
warmup_epoch: 20

max_lr: 0.001
init_lr: 0.0001
andness_init_lr: 0.001

weight_decay: 0.001

temp: 0.01

logic_name: AIWA
log_iter: 500

alpha: 0.999
beta: 8
gamma: 1

bound: 0.1
eps: 1.0e-3

dropout_p: 0.1