defaults:
  - base_rrl
  - _self_

batch_size: 128

structure: 10@256

epoch: 200
lr_decay_rate: 0.75
lr_decay_epoch: 100
warmup_epoch: 20

learning_rate: 0.002

weight_decay: 0.001

nlaf: true
alpha: 0.999
beta: 8
gamma: 1

temp: 0.01