# @package _global_

dataset:
  preprocess_name: Archaic-UCI

preprocess:
  features:
    - K9

model:
  batch_size: 128
  structure: 10@1024
  max_lr: 0.001
  init_lr: 0.0001
  logic_name: AndnessRRL
  log_iter: 5000
  dropout_p: 0.1

train:
  plot_roc: true