# @package _global_

dataset:
  preprocess_name: Archaic-NIPS

preprocess:
  features:
    - all

model:
  batch_size: 8
  structure: 10@1024
  max_lr: 0.005
  init_lr: 0.0005
  logic_name: AndnessRRL
  log_iter: 500
  dropout_p: 0.1

train:
  plot_roc: true